#!/bin/sh
echo You must edit runjython to set the correct environment before you
echo can run this script 
exit
# Edit the JYTHON=, and DTSL_LIBS= lines below to be correct 
# for your system then delete the previous 3 lines
# JYTHON should be set to the location of your Jython installation
JYTHON="/home/tony/jython2.5.3"
DTSL_LIBS="./libs"
JAVALIBS="${DTSL_LIBS}/arm/*:${DTSL_LIBS}/tpip/*:${DTSL_LIBS}/arm/com.arm.rddi.native"
CP="${JAVALIBS}:${CLASSPATH}"
export JYTHONPATH="./src"
SCRIPT=$1
shift
COMMAND="${JYTHON}/jython -J-classpath ${CP} src/${SCRIPT}.py $@"
echo src/${SCRIPT}.py $@
exec ${COMMAND}
