# Copyright (C) 2013-2014,2017 Arm Limited (or its affiliates). All rights reserved.

# Import all!
from osapi import *

# uCOS-III Global Variables (add all possible variations for the name - this may change with different OS versions!)
OS_APP_IDLE_TASK_HOOK_PTR               = [ "OS_AppIdleTaskHookPtr"           ]
OS_APP_STAT_TASK_HOOK_PTR               = [ "OS_AppStatTaskHookPtr"           ]
OS_APP_TASK_CREATE_HOOK_PTR             = [ "OS_AppTaskCreateHookPtr"         ]
OS_APP_TASK_DEL_HOOK_PTR                = [ "OS_AppTaskDelHookPtr"            ]
OS_APP_TASK_RETURN_HOOK_PTR             = [ "OS_AppTaskReturnHookPtr"         ]
OS_APP_TASK_SW_HOOK_PTR                 = [ "OS_AppTaskSwHookPtr"             ]
OS_APP_TIME_TICK_HOOK_PTR               = [ "OS_AppTimeTickHookPtr"           ]
OS_FLAG_DBG_LIST_PTR                    = [ "OSFlagDbgListPtr"                ]
OS_FLAG_QTY                             = [ "OSFlagQty"                       ]
OS_IDLE_TASK_CTR                        = [ "OSIdleTaskCtr"                   ]
OS_IDLE_TASK_TCB                        = [ "OSIdleTaskTCB"                   ]
OS_INT_DIS_TIME_MAX                     = [ "OSIntDisTimeMax"                 ]
OS_INT_NESTING_CTR                      = [ "OSIntNestingCtr"                 ]
OS_INT_Q_IN_PTR                         = [ "OSIntQInPtr"                     ]
OS_INT_Q_NBR_ENTRIESMAX                 = [ "OSIntQNbrEntriesMax"             ]
OS_INT_Q_NBR_ENTRIES                    = [ "OSIntQNbrEntries"                ]
OS_INT_Q_OUT_PTR                        = [ "OSIntQOutPtr"                    ]
OS_INT_Q_OVF_CTR                        = [ "OSIntQOvfCtr"                    ]
OS_INT_Q_TASK_TCB                       = [ "OSIntQTaskTCB"                   ]
OS_INT_Q_TASK_TIMEMAX                   = [ "OSIntQTaskTimeMax"               ]
OS_MEM_DBG_LIST_PTR                     = [ "OSMemDbgListPtr"                 ]
OS_MEM_QTY                              = [ "OSMemQty"                        ]
OS_MSG_POOL                             = [ "OSMsgPool"                       ]
OS_MUTEX_DBG_LIST_PTR                   = [ "OSMutexDbgListPtr"               ]
OS_MUTEX_QTY                            = [ "OSMutexQty"                      ]
OS_PRIO_CUR                             = [ "OSPrioCur"                       ]
OS_PRIO_HIGHRDY                         = [ "OSPrioHighRdy"                   ]
OS_PRIO_SAVED                           = [ "OSPrioSaved"                     ]
OS_PRIO_TBL                             = [ "OSPrioTbl"                       ]
OS_Q_DBG_LIST_PTR                       = [ "OSQDbgListPtr"                   ]
OS_Q_QTY                                = [ "OSQQty"                          ]
OS_RDY_LIST                             = [ "OSRdyList"                       ]
OS_RUNNING                              = [ "OSRunning"                       ]
OS_SAFETY_CRITICAL_START_FLAG           = [ "OSSafetyCriticalStartFlag"       ]
OS_SCHED_LOCK_NESTING_CTR               = [ "OSSchedLockNestingCtr"           ]
OS_SCHED_LOCK_TIME_BEGIN                = [ "OSSchedLockTimeBegin"            ]
OS_SCHED_LOCK_TIME_MAX_CUR              = [ "OSSchedLockTimeMaxCur"           ]
OS_SCHED_LOCK_TIME_MAX                  = [ "OSSchedLockTimeMax"              ]
OS_SCHED_ROUND_ROBIN_DFLT_TIME_QUANTA   = [ "OSSchedRoundRobinDfltTimeQuanta" ]
OS_SCHED_ROUND_ROBIN_EN                 = [ "OSSchedRoundRobinEn"             ]
OS_SEM_DBG_LIST_PTR                     = [ "OSSemDbgListPtr"                 ]
OS_SEM_QTY                              = [ "OSSemQty"                        ]
OS_STAT_RESET_FLAG                      = [ "OSStatResetFlag"                 ]
OS_STAT_TASK_CPU_USAGE_MAX              = [ "OSStatTaskCPUUsageMax"           ]
OS_STAT_TASK_CPU_USAGE                  = [ "OSStatTaskCPUUsage"              ]
OS_STAT_TASK_CTR_MAX                    = [ "OSStatTaskCtrMax"                ]
OS_STAT_TASK_CTR                        = [ "OSStatTaskCtr"                   ]
OS_STAT_TASK_CTR_RUN                    = [ "OSStatTaskCtrRun"                ]
OS_STAT_TASK_RDY                        = [ "OSStatTaskRdy"                   ]
OS_STAT_TASK_TCB                        = [ "OSStatTaskTCB"                   ]
OS_STAT_TASK_TIME_MAX                   = [ "OSStatTaskTimeMax"               ]
OS_TASK_CTX_SW_CTR                      = [ "OSTaskCtxSwCtr"                  ]
OS_TASK_DBG_LIST_PTR                    = [ "OSTaskDbgListPtr"                ]
OS_TASK_QTY                             = [ "OSTaskQty"                       ]
OS_TASK_REG_NEXT_AVAIL_ID               = [ "OSTaskRegNextAvailID"            ]
OS_TCB_CUR_PTR                          = [ "OSTCBCurPtr"                     ]
OS_TCB_HIGH_RDY_PTR                     = [ "OSTCBHighRdyPtr"                 ]
OS_TICK_CTR                             = [ "OSTickCtr"                       ]
OS_TICK_LIST_DLY                        = [ "OSTickListDly"                   ]
OS_TICK_LIST_TIMEOUT                    = [ "OSTickListTimeout"               ]
OS_TICK_TASK_TCB                        = [ "OSTickTaskTCB"                   ]
OS_TICK_TASK_TIME_MAX                   = [ "OSTickTaskTimeMax"               ]
OS_TMR_DBG_LIST_PTR                     = [ "OSTmrDbgListPtr"                 ]
OS_TMR_LIST_ENTRIES                     = [ "OSTmrListEntries"                ]
OS_TMR_LIST_PTR                         = [ "OSTmrListPtr"                    ]
OS_TMR_MUTEX                            = [ "OSTmrMutex"                      ]
OS_TMR_QTY                              = [ "OSTmrQty"                        ]
OS_TMR_TASK_TCB                         = [ "OSTmrTaskTCB"                    ]
OS_TMR_TASK_TIME_MAX                    = [ "OSTmrTaskTimeMax"                ]
OS_TMR_TICK_CTR                         = [ "OSTmrTickCtr"                    ]
OS_TMR_UPDATE_CNT                       = [ "OSTmrUpdateCnt"                  ]
OS_TMR_UPDATE_CTR                       = [ "OSTmrUpdateCtr"                  ]
OSDBG_APP_HOOK_SEN                      = [ "OSDbg_AppHooksEn"                ]
OSDBG_ARG_CHK_EN                        = [ "OSDbg_ArgChkEn"                  ]
OSDBG_CALLED_FROM_ISR_CHK_EN            = [ "OSDbg_CalledFromISRChkEn"        ]
OSDBG_ENDIANNESS_TEST                   = [ "OSDbg_EndiannessTest"            ]
OSDBG_FLAG_DEL_EN                       = [ "OSDbg_FlagDelEn"                 ]
OSDBG_FLAG_EN                           = [ "OSDbg_FlagEn"                    ]
OSDBG_FLAG_GRP                          = [ "OSDbg_FlagGrp"                   ]
OSDBG_FLAG_GRP_SIZE                     = [ "OSDbg_FlagGrpSize"               ]
OSDBG_FLAG_MODE_CLR_EN                  = [ "OSDbg_FlagModeClrEn"             ]
OSDBG_FLAG_PEND_ABORT_EN                = [ "OSDbg_FlagPendAbortEn"           ]
OSDBG_FLAG_WIDTH                        = [ "OSDbg_FlagWidth"                 ]
OSDBG_INT_Q                             = [ "OSDbg_IntQ"                      ]
OSDBG_ISR_POST_DEFERRED_EN              = [ "OSDbg_ISRPostDeferredEn"         ]
OSDBG_MEM_EN                            = [ "OSDbg_MemEn"                     ]
OSDBG_MEM                               = [ "OSDbg_Mem"                       ]
OSDBG_MEM_SIZE                          = [ "OSDbg_MemSize"                   ]
OSDBG_MSG_EN                            = [ "OSDbg_MsgEn"                     ]
OSDBG_MSG_POOL_SIZE                     = [ "OSDbg_MsgPoolSize"               ]
OSDBG_MSG_Q_SIZE                        = [ "OSDbg_MsgQSize"                  ]
OSDBG_MSG_SIZE                          = [ "OSDbg_MsgSize"                   ]
OSDBG_MUTEX_DEL_EN                      = [ "OSDbg_MutexDelEn"                ]
OSDBG_MUTEX_EN                          = [ "OSDbg_MutexEn"                   ]
OSDBG_MUTEX                             = [ "OSDbg_Mutex"                     ]
OSDBG_MUTEX_PEND_ABOR_TEN               = [ "OSDbg_MutexPendAbortEn"          ]
OSDBG_MUTEX_SIZE                        = [ "OSDbg_MutexSize"                 ]
OSDBG_OBJ_TYPE_CHK_EN                   = [ "OSDbg_ObjTypeChkEn"              ]
OSDBG_PEND_DATA_SIZE                    = [ "OSDbg_PendDataSize"              ]
OSDBG_PEND_LIST_SIZE                    = [ "OSDbg_PendListSize"              ]
OSDBG_PEND_MULTI_EN                     = [ "OSDbg_PendMultiEn"               ]
OSDBG_PEND_OBJ_SIZE                     = [ "OSDbg_PendObjSize"               ]
OSDBG_PRIO_MAX                          = [ "OSDbg_PrioMax"                   ]
OSDBG_PRIO_TBL_SIZE                     = [ "OSDbg_PrioTblSize"               ]
OSDBG_PTR_SIZE                          = [ "OSDbg_PtrSize"                   ]
OSDBG_Q_DEL_EN                          = [ "OSDbg_QDelEn"                    ]
OSDBG_Q_EN                              = [ "OSDbg_QEn"                       ]
OSDBG_Q_FLUSH_EN                        = [ "OSDbg_QFlushEn"                  ]
OSDBG_Q                                 = [ "OSDbg_Q"                         ]
OSDBG_Q_PEND_ABORT_EN                   = [ "OSDbg_QPendAbortEn"              ]
OSDBG_Q_SIZE                            = [ "OSDbg_QSize"                     ]
OSDBG_RDY_LIST                          = [ "OSDbg_RdyList"                   ]
OSDBG_RDY_LIST_SIZE                     = [ "OSDbg_RdyListSize"               ]
OSDBG_SCHED_ROUND_ROBIN_EN              = [ "OSDbg_SchedRoundRobinEn"         ]
OSDBG_SEM_DEL_EN                        = [ "OSDbg_SemDelEn"                  ]
OSDBG_SEM_EN                            = [ "OSDbg_SemEn"                     ]
OSDBG_SEM                               = [ "OSDbg_Sem"                       ]
OSDBG_SEM_PEND_ABORT_EN                 = [ "OSDbg_SemPendAbortEn"            ]
OSDBG_SEM_SET_EN                        = [ "OSDbg_SemSetEn"                  ]
OSDBG_SEM_SIZE                          = [ "OSDbg_SemSize"                   ]
OSDBG_STAT_TASK_EN                      = [ "OSDbg_StatTaskEn"                ]
OSDBG_STAT_TASK_STK_CHK_EN              = [ "OSDbg_StatTaskStkChkEn"          ]
OSDBG_STK_WIDTH                         = [ "OSDbg_StkWidth"                  ]
OSDBG_TASK_CHANGE_PRIO_EN               = [ "OSDbg_TaskChangePrioEn"          ]
OSDBG_TASK_DEL_EN                       = [ "OSDbg_TaskDelEn"                 ]
OSDBG_TASK_PROFILE_EN                   = [ "OSDbg_TaskProfileEn"             ]
OSDBG_TASK_Q_EN                         = [ "OSDbg_TaskQEn"                   ]
OSDBG_TASK_Q_PEND_ABORT_EN              = [ "OSDbg_TaskQPendAbortEn"          ]
OSDBG_TASK_REG_TBL_SIZE                 = [ "OSDbg_TaskRegTblSize"            ]
OSDBG_TASK_SEM_PEND_ABORT_EN            = [ "OSDbg_TaskSemPendAbortEn"        ]
OSDBG_TASK_SUSPEND_EN                   = [ "OSDbg_TaskSuspendEn"             ]
OSDBG_TCB_SIZE                          = [ "OSDbg_TCBSize"                   ]
OSDBG_TICK_LIST_SIZE                    = [ "OSDbg_TickListSize"              ]
OSDBG_TIME_DLY_HMSM_EN                  = [ "OSDbg_TimeDlyHMSMEn"             ]
OSDBG_TIME_DLY_RESUME_EN                = [ "OSDbg_TimeDlyResumeEn"           ]
OSDBG_TLS_TBL_SIZE                      = [ "OSDbg_TLS_TblSize"               ]
OSDBG_TMR_DEL_EN                        = [ "OSDbg_TmrDelEn"                  ]
OSDBG_TMR_EN                            = [ "OSDbg_TmrEn"                     ]
OSDBG_TMR                               = [ "OSDbg_Tmr"                       ]
OSDBG_TMR_SIZE                          = [ "OSDbg_TmrSize"                   ]
OSDBG_TMR_SIZE                          = [ "OSDbg_TmrSize"                   ]
OSDBG_VERSIONNBR                        = [ "OSDbg_VersionNbr"                ]

# uCOS-III structure names
OS_INT_Q                                = "os_int_q"
OS_RDY_LIST                             = "os_rdy_list"
OS_PEND_DATA                            = "os_pend_data"
OS_PEND_LIST                            = "os_pend_list"
OS_PEND_OBJ                             = "os_pend_obj"
OS_FLAG_GRP                             = "os_flag_grp"
OS_MEM                                  = "os_mem"
OS_MSG                                  = "os_msg"
OS_MSG_POOL                             = "os_msg_pool"
OS_MSG_Q                                = "os_msg_q"
OS_MUTEX                                = "os_mutex"
OS_Q                                    = "os_q"
OS_SEM                                  = "os_sem"
OS_TCB                                  = "os_tcb"
OS_TICK_LIST                            = "os_tick_list"
OS_TMR                                  = "os_tmr"

# ISR post data structure
OS_INT_Q_TYPE                           = [ "Type"    ]
OS_INT_Q_NEXT_PTR                       = [ "NextPtr" ]
OS_INT_Q_OBJ_PTR                        = [ "ObjPtr"  ]
OS_INT_Q_MSG_PTR                        = [ "MsgPtr"  ]
OS_INT_Q_MSG_SIZE                       = [ "MsgSize" ]
OS_INT_Q_FLAGS                          = [ "Flags"   ]
OS_INT_Q_OPT                            = [ "Opt"     ]
OS_INT_Q_TS                             = [ "TS"      ]

# Ready list structure
OS_RDY_LIST_HEAD_PTR                    = [ "HeadPtr"    ]
OS_RDY_LIST_TAIL_PTR                    = [ "TailPtr"    ]
OS_RDY_LIST_NBR_ENTRIES                 = [ "NbrEntries" ]

# Pend data structure
OS_PEND_DATA_PREV_PTR                   = [ "PrevPtr"    ]
OS_PEND_DATA_NEXT_PTR                   = [ "NextPtr"    ]
OS_PEND_DATA_TCB_PTR                    = [ "TCBPtr"     ]
OS_PEND_DATA_PEND_OBJ_PTR               = [ "PendObjPtr" ]
OS_PEND_DATA_RDY_OBJ_PTR                = [ "RdyObjPtr"  ]
OS_PEND_DATA_RDY_MSG_PTR                = [ "RdyMsgPtr"  ]
OS_PEND_DATA_RDY_MSG_SIZE               = [ "RdyMsgSize" ]
OS_PEND_DATA_RDY_TS                     = [ "RdyTS"      ]

# Pend list structure
OS_PEND_LIST_HEAD_PTR                   = [ "HeadPtr"    ]
OS_PEND_LIST_TAIL_PTR                   = [ "TailPtr"    ]
OS_PEND_LIST_NBR_ENTRIES                = [ "NbrEntries" ]

# Pend object structure
OS_PEND_OBJ_TYPE                        = [ "Type"       ]
OS_PEND_OBJ_NAME_PTR                    = [ "NamePtr"    ]
OS_PEND_OBJ_PEND_LIST                   = [ "PendList"   ]
OS_PEND_OBJ_DBG_PREV_PTR                = [ "DbgPrevPtr" ]
OS_PEND_OBJ_DBG_NEXT_PTR                = [ "DbgNextPtr" ]
OS_PEND_OBJ_DBG_NAME_PTR                = [ "DbgNamePtr" ]

# Event flags
OS_FLAG_GRP_TYPE                        = [ "Type"       ]
OS_FLAG_GRP_NAME_PTR                    = [ "NamePtr"    ]
OS_FLAG_GRP_PEND_LIST                   = [ "PendList"   ]
OS_FLAG_GRP_DBG_PREV_PTR                = [ "DbgPrevPtr" ]
OS_FLAG_GRP_DBG_NEXT_PTR                = [ "DbgNextPtr" ]
OS_FLAG_GRP_DBG_NAME_PTR                = [ "DbgNamePtr" ]
OS_FLAG_GRP_FLAGS                       = [ "Flags"      ]
OS_FLAG_GRP_TS                          = [ "TS"         ]
OS_FLAG_GRP_FLAG_ID                     = [ "FlagID"     ]

# Memory partitions structure
OS_MEM_TYPE                             = [ "Type"        ]
OS_MEM_ADDR_PTR                         = [ "AddrPtr"     ]
OS_MEM_NAME_PTR                         = [ "NamePtr"     ]
OS_MEM_FREE_LIST_PTR                    = [ "FreeListPtr" ]
OS_MEM_BLK_SIZE                         = [ "BlkSize"     ]
OS_MEM_NBR_MAX                          = [ "NbrMax"      ]
OS_MEM_NBR_FREE                         = [ "NbrFree"     ]
OS_MEM_DBG_PREV_PTR                     = [ "DbgPrevPtr"  ]
OS_MEM_DBG_NEXT_PTR                     = [ "DbgNextPtr"  ]
OS_MEM_MEM_ID                           = [ "MemID"       ]

# Message structure
OS_MSG_NEXT_PTR                         = [ "NextPtr" ]
OS_MSG_MSG_PTR                          = [ "MsgPtr"  ]
OS_MSG_MSG_SIZE                         = [ "MsgSize" ]
OS_MSG_MSG_TS                           = [ "MsgTS"   ]

# Message pool structure
OS_MSG_POOL_NEXT_PTR                    = [ "NextPtr"    ]
OS_MSG_POOL_NBR_FREE                    = [ "NbrFree"    ]
OS_MSG_POOL_NBR_USED                    = [ "NbrUsed"    ]
OS_MSG_POOL_NBR_USED_MAX                = [ "NbrUsedMax" ]

#  Message queue structure
OS_MSG_Q_IN_PTR                         = [ "InPtr"          ]
OS_MSG_Q_OUT_PTR                        = [ "OutPtr"         ]
OS_MSG_Q_NBR_ENTRIES_SIZE               = [ "NbrEntriesSize" ]
OS_MSG_Q_NBR_ENTRIES                    = [ "NbrEntries"     ]
OS_MSG_Q_NBR_ENTRIES_MAX                = [ "NbrEntriesMax"  ]
OS_MSG_Q_MSG_Q_ID                       = [ "MsgQID"         ]

# Mutex structure
OS_MUTEX_TYPE                           = [ "Type"              ]
OS_MUTEX_NAME_PTR                       = [ "NamePtr"           ]
OS_MUTEX_PEND_LIST                      = [ "PendList"          ]
OS_MUTEX_DBG_PREV_PTR                   = [ "DbgPrevPtr"        ]
OS_MUTEX_DBG_NEXT_PTR                   = [ "DbgNextPtr"        ]
OS_MUTEX_DBG_NAME_PTR                   = [ "DbgNamePtr"        ]
OS_MUTEX_OWNER_TCB_PTR                  = [ "OwnerTCBPtr"       ]
OS_MUTEX_OWNER_ORIGINAL_PRIO            = [ "OwnerOriginalPrio" ]
OS_MUTEX_OWNER_NESTING_CTR              = [ "OwnerNestingCtr"   ]
OS_MUTEX_TS                             = [ "TS"                ]
OS_MUTEX_MUTEX_ID                       = [ "MutexID"           ]

# Message queue structure
OS_Q_TYPE                               = [ "Type"       ]
OS_Q_NAME_PTR                           = [ "NamePtr"    ]
OS_Q_PEND_LIST                          = [ "PendList"   ]
OS_Q_DBG_PREV_PTR                       = [ "DbgPrevPtr" ]
OS_Q_DBG_NEXT_PTR                       = [ "DbgNextPtr" ]
OS_Q_DBG_NAME_PTR                       = [ "DbgNamePtr" ]
OS_Q_MSG_Q                              = [ "MsgQ"       ]
OS_Q_MSG_Q_ID                           = [ "MsgQID"     ]

# Semaphore structure
OS_SEM_TYPE                             = [ "Type"       ]
OS_SEM_NAME_PTR                         = [ "NamePtr"    ]
OS_SEM_PEND_LIST                        = [ "PendList"   ]
OS_SEM_DBG_PREV_PTR                     = [ "DbgPrevPtr" ]
OS_SEM_DBG_NEXT_PTR                     = [ "DbgNextPtr" ]
OS_SEM_DBG_NAME_PTR                     = [ "DbgNamePtr" ]
OS_SEM_CTR                              = [ "Ctr"        ]
OS_SEM_TS                               = [ "TS"         ]
OS_SEM_SEM_ID                           = [ "SemID"      ]

# Task control block structure
OS_TCB_STK_PTR                          = [ "StkPtr"             ]
OS_TCB_EXT_PTR                          = [ "ExtPtr"             ]
OS_TCB_STK_LIMIT_PTR                    = [ "StkLimitPtr"        ]
OS_TCB_NEXT_PTR                         = [ "NextPtr"            ]
OS_TCB_PREV_PTR                         = [ "PrevPtr"            ]
OS_TCB_TICK_NEXT_PTR                    = [ "TickNextPtr"        ]
OS_TCB_TICK_PREV_PTR                    = [ "TickPrevPtr"        ]
OS_TCB_TICK_LIST_PTR                    = [ "TickListPtr", "TickSpokePtr" ]
OS_TCB_NAME_PTR                         = [ "NamePtr"            ]
OS_TCB_STK_BASE_PTR                     = [ "StkBasePtr"         ]
OS_TCB_TLS_TBL                          = [ "TLS_Tbl"            ]
OS_TCB_TASK_ENTRY_ADDR                  = [ "TaskEntryAddr"      ]
OS_TCB_TASK_ENTRY_ARG                   = [ "TaskEntryArg"       ]
OS_TCB_PEND_DATA_TBL_PTR                = [ "PendDataTblPtr"     ]
OS_TCB_PEND_ON                          = [ "PendOn"             ]
OS_TCB_PEND_STATUS                      = [ "PendStatus"         ]
OS_TCB_TASK_STATE                       = [ "TaskState"          ]
OS_TCB_PRIO                             = [ "Prio"               ]
OS_TCB_STK_SIZE                         = [ "StkSize"            ]
OS_TCB_OPT                              = [ "Opt"                ]
OS_TCB_PEND_DATA_TBL_ENTRIES            = [ "PendDataTblEntries" ]
OS_TCB_TS                               = [ "TS"                 ]
OS_TCB_SEM_ID                           = [ "SemID"              ]
OS_TCB_SEM_CTR                          = [ "SemCtr"             ]
OS_TCB_TICK_REMAIN                      = [ "TickRemain"         ]
OS_TCB_TICK_CTR_PREV                    = [ "TickCtrPrev"        ]
OS_TCB_TICK_MATCH                       = [ "TickCtrMatch"       ]
OS_TCB_TIME_QUANTA                      = [ "TimeQuanta"         ]
OS_TCB_TIME_QUANTA_CTR                  = [ "TimeQuantaCtr"      ]
OS_TCB_MSG_PTR                          = [ "MsgPtr"             ]
OS_TCB_MSG_SIZE                         = [ "MsgSize"            ]
OS_TCB_MSG_Q                            = [ "MsgQ"               ]
OS_TCB_MSG_Q_PEND_TIME                  = [ "MsgQPendTime"       ]
OS_TCB_MSG_Q_PEND_TIME_MAX              = [ "MsgQPendTimeMax"    ]
OS_TCB_REG_TBL                          = [ "RegTbl"             ]
OS_TCB_FLAGS_PEND                       = [ "FlagsPend"          ]
OS_TCB_FLAGS_RDY                        = [ "FlagsRdy"           ]
OS_TCB_FLAGS_OPT                        = [ "FlagsOpt"           ]
OS_TCB_SUSPEND_CTR                      = [ "SuspendCtr"         ]
OS_TCB_CPU_USAGE                        = [ "CPUUsage"           ]
OS_TCB_CPU_USAGE_MAX                    = [ "CPUUsageMax"        ]
OS_TCB_CTX_SW_CTR                       = [ "CtxSwCtr"           ]
OS_TCB_CYCLES_DELTA                     = [ "CyclesDelta"        ]
OS_TCB_CYCLES_START                     = [ "CyclesStart"        ]
OS_TCB_CYCLES_TOTAL                     = [ "CyclesTotal"        ]
OS_TCB_CYCLES_TOTAL_PREV                = [ "CyclesTotalPrev"    ]
OS_TCB_SEM_PEND_TIME                    = [ "SemPendTime"        ]
OS_TCB_SEM_PEND_TIME_MAX                = [ "SemPendTimeMax"     ]
OS_TCB_STK_USED                         = [ "StkUsed"            ]
OS_TCB_STK_FREE                         = [ "StkFree"            ]
OS_TCB_INT_DIS_TIME_MAX                 = [ "IntDisTimeMax"      ]
OS_TCB_SCHED_LOCK_TIME_MAX              = [ "SchedLockTimeMax"   ]
OS_TCB_DBG_PREV_PTR                     = [ "DbgPrevPtr"         ]
OS_TCB_DBG_NEXT_PTR                     = [ "DbgNextPtr"         ]
OS_TCB_DBG_NAME_PTR                     = [ "DbgNamePtr"         ]
OS_TCB_TASK_ID                          = [ "TaskID"             ]

# Tick list
OS_TICK_LIST_TCB_PTR                    = [ "TCB_Ptr"    ]
OS_TICK_LIST_NBR_ENTRIES                = [ "NbrEntries" ]
OS_TICK_LIST_NBR_UPDATED                = [ "NbrUpdated" ]

# Timer structure
OS_TMR_TYPE                             = [ "Type"           ]
OS_TMR_NAME_PTR                         = [ "NamePtr"        ]
OS_TMR_CALLBACK_PTR                     = [ "CallbackPtr"    ]
OS_TMR_CALLBACK_PTR_ARG                 = [ "CallbackPtrArg" ]
OS_TMR_NEXT_PTR                         = [ "NextPtr"        ]
OS_TMR_PREV_PTR                         = [ "PrevPtr"        ]
OS_TMR_MATCH                            = [ "Match"          ]
OS_TMR_REMAIN                           = [ "Remain"         ]
OS_TMR_DLY                              = [ "Dly"            ]
OS_TMR_PERIOD                           = [ "Period"         ]
OS_TMR_OPT                              = [ "Opt"            ]
OS_TMR_STATE                            = [ "State"          ]
OS_TMR_DBG_PREV_PTR                     = [ "DbgPrevPtr"     ]
OS_TMR_DBG_NEXT_PTR                     = [ "DbgNextPtr"     ]

# Function names
OS_CPU_ARM_DREG_CNT_GET                 = [ "OS_CPU_ARM_DRegCntGet" ]
OS_CPU_FP_REG_PUSH                      = [ "OS_CPU_FP_Reg_Push"    ]

# Get global variable from a list of possible names
def globGetName( glob, debugSession ):
    name = ""   # Default return value
    # Step through all possible names for a given variable
    for g in glob:
        # Check if exists
        if debugSession.symbolExists( g ):
            name = g    # Yes, save
            break       # and stop looking
    return name     # Variable name
